inventory/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = 'inventory'

urlpatterns = [
    path('list/items/', views.itemList, name='items_list'),
    path('list/drugs/', views.drugList, name='drugs_list'),
    path('item/', views.ItemPage, name='addItem'),
    path('drug/', views.DrugPage, name='addDrug'),
    url(r'^delete/(?P<id>[\w.@+-]+)/$', views.delete_item, name='deleteItem'),
    url(r'^delete_drug/(?P<id>[\w.@+-]+)/$', views.delete_drug, name='deleteDrug'),
    url(r'^edit/(?P<id>[\w.@+-]+)/$', views.edit_item, name='editItem'),
    url(r'^edit_drug/(?P<id>[\w.@+-]+)/$', views.edit_drug, name='editDrug'),

]

users/urls.py
from django.urls import path

from users.views import DoctorListView, ClientListView, NurseListView,PatientListView
from . import views
from django.conf.urls import url
app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    # path('doctors/', views.DoctorListView, name='doctorList'),

    url(r'^clients/', ClientListView.as_view(), name='clientList'),
    url(r'^doctors/', DoctorListView.as_view(), name='doctorList'),

    url(r'^patients-all/', PatientListView.as_view(), name='patientListAll'),
    url(r'^patients-warded/', views.PatientList, name='patientList'),
    url(r'^nurses/', NurseListView.as_view(), name='nurseList'),
    url(r'^profile/(?P<username>[\w.@+-]+)/$', views.get_user_profile, name='profile'),
    path('add_user/', views.SignUp, name='addUser'),
    url(r'^delete/(?P<username>[\w.@+-]+)/$', views.delete, name='delete'),

    # url(r'^profile/(?P<username>[\w.@+-]+)/$', views.get_user_profile, name='profile'),
    url(r'^edit/(?P<username>[\w.@+-]+)/$', views.edit_profile, name='edit_profile'),
    url(r'^edits/(?P<username>[\w.@+-]+)/$', views.edit, name='editProfile'),
    # path('edit/', views.edit_profile, name='edit_profile'),
]

templates/containers/layouts/sidenavbar/item_sidenavbar.html
{% load static %}

<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-dashboards"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-dashboards"
    >
      <i class="fas fa-chart-bar text-primary"></i>
      <span class="nav-link-text">Dashboards</span>
    </a>
    <div class="collapse" id="navbar-dashboards">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">Patients</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Analytics</a>
        </li>
      </ul>
    </div>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">List</h6>
<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-doctors"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-doctors"
    >
      <i class="fas fa-user-md text-info"></i>
      <span class="nav-link-text">Doctors</span>
    </a>
    <div class="collapse" id="navbar-doctors">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">Add New Doctors</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">View All Doctors</a>
        </li>
      </ul>
    </div>
  </li>
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-patients"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-patients"
    >
      <i class="fas fa-procedures text-info"></i>
      <span class="nav-link-text">Patients</span>
    </a>
    <div class="collapse" id="navbar-patients">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">Add New Patient</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">View All Patients</a>
        </li>
      </ul>
    </div>
  </li>
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-nurses"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-inventory"
    >
      <i class="fas fa-user-nurse text-info"></i>
      <span class="nav-link-text">Nurses</span>
    </a>
    <div class="collapse" id="navbar-nurses">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">Add New Nurse</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">View All Nurses</a>
        </li>
      </ul>
    </div>
  </li>
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-inventory"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-inventory"
    >
      <i class="fas fa-boxes text-info"></i>
      <span class="nav-link-text">Inventory</span>
    </a>
    <div class="collapse" id="navbar-inventory">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link">Add New Item</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">View All Medical Items</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">View All Medical Drugs</a>
        </li>
      </ul>
    </div>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">User Manual</h6>
<ul class="navbar-nav mb-md-3">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#"
      target="_blank"
    >
      <i class="far fa-file-pdf text-success"></i>
      <span class="nav-link-text">Documentation</span>
    </a>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">Profile</h6>
<ul class="navbar-nav mb-md-3">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#"
    >
      <i class="far fa-id-card text-warning"></i>
      <span class="nav-link-text">Profile</span>
    </a>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">Misc.</h6>
<ul class="navbar-nav mb-md-3">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#"
    >
      <i class="far fa-id-card text-warning"></i>
      <span class="nav-link-text">Calendar</span>
    </a>
  </li>
</ul>

templates/containers/layouts/sidenavbar/item_sidenavbar_admin.html
{% load static %}

<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-dashboards"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-dashboards"
    >
      <i class="fas fa-chart-bar text-primary"></i>
      <span class="nav-link-text">Dashboards</span>
    </a>
    <div class="collapse" id="navbar-dashboards">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'clientDashboard' %}" class="nav-link">Client</a>
        </li>
      </ul>
    </div>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">List</h6>
<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-doctors"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-doctors"
    >
      <i class="fas fa-user-md text-info"></i>
      <span class="nav-link-text">Clients</span>
    </a>
    <div class="collapse" id="navbar-doctors">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'users:addUser'%}" class="nav-link">Add New Client</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'users:clientList' %}" class="nav-link">View All Client</a>
        </li>
      </ul>
    </div>
  </li>
</ul>

templates/containers/layouts/sidenavbar/item_sidenavbar_client.html
{% load static %}

<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-dashboards"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-dashboards"
    >
      <i class="fas fa-chart-bar text-primary"></i>
      <span class="nav-link-text">Dashboards</span>
    </a>
    <div class="collapse" id="navbar-dashboards">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'dashboard' %}" class="nav-link">Patients</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'analyticDashboard' %}" class="nav-link">Analytics</a>
        </li>
      </ul>
    </div>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">List</h6>
<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-doctors"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-doctors"
    >
      <i class="fas fa-user-md text-info"></i>
      <span class="nav-link-text">Doctors/Nurses</span>
    </a>
    <div class="collapse" id="navbar-doctors">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'users:addUser'%}" class="nav-link">Add New Doctor/Nurse</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'users:doctorList' %}" class="nav-link">View All Doctors</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'users:nurseList' %}" class="nav-link">View All Nurses</a>
        </li>

      </ul>


    </div>


      <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-inventory"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-inventory"
    >
      <i class="fas fa-boxes text-info"></i>
      <span class="nav-link-text">Inventory</span>
    </a>
    <div class="collapse" id="navbar-inventory">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'inventory:addItem' %}" class="nav-link">Add New Item</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:addDrug' %}" class="nav-link">Add New Drug</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:items_list' %}" class="nav-link">View All Medical Items</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:drugs_list' %}" class="nav-link">View All Medical Drugs</a>
        </li>


  </li>
</ul>

templates/containers/layouts/sidenavbar/item_sidenavbar_doctor.html
{% load static %}

<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-dashboards"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-dashboards"
    >
      <i class="fas fa-chart-bar text-primary"></i>
      <span class="nav-link-text">Dashboards</span>
    </a>
    <div class="collapse" id="navbar-dashboards">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'dashboard' %}" class="nav-link">Patients</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'analyticDashboard' %}" class="nav-link">Analytics</a>
        </li>
      </ul>
    </div>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">List</h6>
<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-doctors"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-doctors"
    >
      <i class="fas fa-user-md text-info"></i>
      <span class="nav-link-text">Patients</span>
    </a>
    <div class="collapse" id="navbar-doctors">
      <ul class="nav nav-sm flex-column">

        <li class="nav-item">
          <a href="{% url 'users:patientList' %}" class="nav-link">View Your Patient</a>
        </li>
      </ul>
    </div>
  </li>
</ul>

templates/containers/layouts/sidenavbar/item_sidenavbar_nurse.html
{% load static %}

<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-dashboards"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-dashboards"
    >
      <i class="fas fa-chart-bar text-primary"></i>
      <span class="nav-link-text">Dashboards</span>
    </a>
    <div class="collapse" id="navbar-dashboards">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'dashboard' %}" class="nav-link">Patients</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'analyticDashboard' %}" class="nav-link">Analytics</a>
        </li>
      </ul>
    </div>
  </li>
</ul>
<hr class="my-3" />
<h6 class="navbar-heading p-0 text-muted">List</h6>
<ul class="navbar-nav">
  <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-doctors"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-doctors"
    >
      <i class="fas fa-user-md text-info"></i>
      <span class="nav-link-text">Patients/Doctors</span>
    </a>
    <div class="collapse" id="navbar-doctors">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'users:addUser'%}" class="nav-link">Add New Patient</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'users:doctorList' %}" class="nav-link">View All Doctors</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'users:patientList' %}" class="nav-link">View All Patient in Ward {{ request.user.ward }}</a>
        </li>

      </ul>


    </div>


      <li class="nav-item">
    <a
      class="nav-link"
      href="#navbar-inventory"
      data-toggle="collapse"
      role="button"
      aria-expanded="false"
      aria-controls="navbar-inventory"
    >
      <i class="fas fa-boxes text-info"></i>
      <span class="nav-link-text">Inventory</span>
    </a>
    <div class="collapse" id="navbar-inventory">
      <ul class="nav nav-sm flex-column">
        <li class="nav-item">
          <a href="{% url 'inventory:addItem' %}" class="nav-link">Add New Item</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:addDrug' %}" class="nav-link">Add New Drug</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:items_list' %}" class="nav-link">View All Medical Items</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'inventory:drugs_list' %}" class="nav-link">View All Medical Drugs</a>
        </li>


  </li>
</ul>

templates/containers/layouts/sidenavbar/main_sidenavbar.html
{% load static %}

<!-- Sidenav -->
<nav
  class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white"
  id="sidenav-main"
>
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header d-flex align-items-center">
      <a class="navbar-brand" href="#">
        <img
          src="{% static 'img/brand/smarthealth102.png' %}"
          class="navbar-brand-img"
          alt="..."
        />
        SH 102
      </a>
      <div class="ml-auto">
        <!-- Sidenav toggler -->
        <div
          class="sidenav-toggler d-none d-xl-block"
          data-action="sidenav-unpin"
          data-target="#sidenav-main"
        >
          <div class="sidenav-toggler-inner">
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        {% if request.user.is_superuser %}
            {% include 'containers/layouts/sidenavbar/item_sidenavbar_admin.html' %}
        {% elif request.user.userType == 'Client' %}
            {% include 'containers/layouts/sidenavbar/item_sidenavbar_client.html' %}
        {% elif request.user.userType == 'Doctor' %}
            {% include 'containers/layouts/sidenavbar/item_sidenavbar_doctor.html' %}
        {% elif request.user.userType == 'Nurse' %}
            {% include 'containers/layouts/sidenavbar/item_sidenavbar_nurse.html' %}
        {% endif %}

        <!-- Divider -->
        
        <!-- Heading -->
        
      </div>
    </div>
  </div>
</nav>