patients/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('list/patients/', views.patientsList, name='patients_list'),
]

users/urls.py
from django.urls import path

from users.views import DoctorListView, ClientListView, NurseListView,PatientListView
from . import views
from django.conf.urls import url
app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    # path('doctors/', views.DoctorListView, name='doctorList'),

    url(r'^clients/', ClientListView.as_view(), name='clientList'),
    url(r'^doctors/', DoctorListView.as_view(), name='doctorList'),

    url(r'^patients-all/', PatientListView.as_view(), name='patientListAll'),
    url(r'^patients-warded/', views.PatientList, name='patientList'),
    url(r'^nurses/', NurseListView.as_view(), name='nurseList'),
    url(r'^profile/(?P<username>[\w.@+-]+)/$', views.get_user_profile, name='profile'),
    path('add_user/', views.SignUp, name='addUser'),
    url(r'^delete/(?P<username>[\w.@+-]+)/$', views.delete, name='delete'),

    # url(r'^profile/(?P<username>[\w.@+-]+)/$', views.get_user_profile, name='profile'),
    url(r'^edit/(?P<username>[\w.@+-]+)/$', views.edit_profile, name='edit_profile'),
    url(r'^edits/(?P<username>[\w.@+-]+)/$', views.edit, name='editProfile'),
    # path('edit/', views.edit_profile, name='edit_profile'),
]

patients/models.py
from django.db import models

# Create your models here.

patients/views.py
from django.shortcuts import render
from .models import *

def patientsList(request):

    patient = Patient.objects.all()
    context = {
        'patient' : patient
    }

    return render(request, 'patients/views/patients_table.html', context)

templates/patients/data/data_patients_table.html
<div class="col">
  <div class="card">
    <!-- Card header -->
    <div class="table-responsive py-4">
      <table class="table table-flush" id="datatable-buttons">
        <thead class="thead-light">
          <tr>
            <th>Medical ID</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Contact Number</th>
            <th>Marital Status</th>
            <th>Birthdate</th>
            <th>Medical Problems</th>
            <th>Medications</th>
            <th>Ward</th>
            <th>Date Joined</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Medical ID</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Contact Number</th>
            <th>Marital Status</th>
            <th>Birthdate</th>
            <th>Medical Problems</th>
            <th>Medications</th>
            <th>Ward</th>
            <th>Date Joined</th>
            <th>Actions</th>
          </tr>
        </tfoot>
        <tbody>
          {% if request.user.userType == 'Nurse' or request.user.userType == 'Doctor' %}
                {% for p in qs %}
          <tr>

            <td>MDHAU{{p.id}}SH102</td>
            <td>{{p.gender}}</td>
            <td>{{p.email}}</td>
            <td>{{p.mobile_number}}</td>
            <td>{{p.maritalStatus}}</td>
            <td>{{p.birthDate}}</td>
            <td>{{p.medicalProblems}}</td>
            <td>{{p.medications}}</td>
            <td>{{p.ward}}</td>
            <td>{{p.date_joined}}</td>
            <td>
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-sm">
                  <a href="{% url 'users:profile' p.username %}">View</a>
                </button>
                <button type="button" class="btn btn-success btn-sm">
                    <a href="{% url 'users:editProfile' p.username%}">Update</a>
                </button>
                <button type="button" class="btn btn-danger btn-sm">
                  <a href="{% url 'users:delete' p.username %}">Delete</a>
                </button>
              </div>
            </td>
          </tr>
          {% endfor %}

          {% elif request.user.userType == 'Client' %}
                {% for p in qs %}
          <tr>

            <td>MDHAU{{p.id}}SH102</td>
            <td>{{p.gender}}</td>
            <td>{{p.email}}</td>
            <td>{{p.mobile_number}}</td>
            <td>{{p.maritalStatus}}</td>
            <td>{{p.birthDate}}</td>
            <td>{{p.medicalProblems}}</td>
            <td>{{p.medications}}</td>
            <td>{{p.ward}}</td>
            <td>{{p.date_joined}}</td>
            <td>
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-sm">
                  <a href="{% url 'users:profile' p.username %}">View</a>
                </button>
                <button type="button" class="btn btn-success btn-sm">
                  Update
                </button>
                <button type="button" class="btn btn-danger btn-sm">
                  <a href="{% url 'users:delete' p.username %}">Delete</a>
                </button>
              </div>
            </td>
          </tr>
          {% endfor %}
          {% endif %}

        </tbody>
      </table>
    </div>
  </div>
</div>